"""
Visualization Utilities for ConvMixer Experiments

This module provides functions for generating publication-quality figures.

Date: 12/13/2025
Written Ke Lu <kl3753@columbia.edu>

The code has not been generated by AI tools, or copied from an exteranal resource.
"""

import matplotlib.pyplot as plt
import numpy as np
import json
import os


def plot_training_curves(history, save_path=None, title='Training Curves'):
    
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    
    epochs = range(1, len(history['train_loss']) + 1)
    
    # Loss
    axes[0].plot(epochs, history['train_loss'], 'b-', linewidth=2)
    axes[0].set_xlabel('Epoch', fontsize=11)
    axes[0].set_ylabel('Loss', fontsize=11)
    axes[0].set_title('Training Loss', fontsize=12)
    axes[0].grid(True, alpha=0.3)
    
    # Accuracy
    axes[1].plot(epochs, history['train_acc'], 'b-', linewidth=2, label='Train')
    axes[1].plot(epochs, history['test_acc'], 'r-', linewidth=2, label='Test')
    axes[1].set_xlabel('Epoch', fontsize=11)
    axes[1].set_ylabel('Accuracy (%)', fontsize=11)
    axes[1].set_title('Accuracy', fontsize=12)
    axes[1].legend(fontsize=10)
    axes[1].grid(True, alpha=0.3)
    
    plt.suptitle(title, fontsize=14)
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.show()


def plot_kernel_size_comparison(our_results, paper_results, save_path=None):
    
    fig, ax = plt.subplots(figsize=(10, 6))
    
    kernel_sizes = sorted(our_results.keys())
    x = np.arange(len(kernel_sizes))
    width = 0.35
    
    our_acc = [our_results[k] for k in kernel_sizes]
    paper_acc = [paper_results[k] for k in kernel_sizes]
    
    bars1 = ax.bar(x - width/2, our_acc, width, label='Our Results', color='steelblue')
    bars2 = ax.bar(x + width/2, paper_acc, width, label='Paper Results', color='coral')
    
    ax.set_xlabel('Kernel Size', fontsize=12)
    ax.set_ylabel('Accuracy (%)', fontsize=12)
    ax.set_title('Kernel Size Ablation: ConvMixer-256/8 on CIFAR-10', fontsize=14)
    ax.set_xticks(x)
    ax.set_xticklabels([f'k={k}' for k in kernel_sizes])
    ax.legend(fontsize=11)
    ax.grid(True, axis='y', alpha=0.3)
    
    # Value labels
    for bar in bars1:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height + 0.2,
                f'{height:.1f}%', ha='center', va='bottom', fontsize=9)
    for bar in bars2:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height + 0.2,
                f'{height:.1f}%', ha='center', va='bottom', fontsize=9)
    
    ax.set_ylim(90, 100)
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.show()


def plot_patch_size_comparison(our_results, paper_results, save_path=None):
   
    fig, ax = plt.subplots(figsize=(8, 6))
    
    patch_sizes = sorted(our_results.keys())
    
    our_acc = [our_results[p] for p in patch_sizes]
    paper_acc = [paper_results[p] for p in patch_sizes]
    
    ax.plot(patch_sizes, our_acc, 'o-', linewidth=2, markersize=10, 
            label='Our Results', color='steelblue')
    ax.plot(patch_sizes, paper_acc, 's--', linewidth=2, markersize=10, 
            label='Paper Results', color='coral')
    
    ax.set_xlabel('Patch Size', fontsize=12)
    ax.set_ylabel('Accuracy (%)', fontsize=12)
    ax.set_title('Patch Size Ablation: ConvMixer-256/8 on CIFAR-10', fontsize=14)
    ax.set_xticks(patch_sizes)
    ax.legend(fontsize=11)
    ax.grid(True, alpha=0.3)
    
    # Add internal resolution annotations
    for p, acc in zip(patch_sizes, our_acc):
        internal_res = 32 // p
        ax.annotate(f'{internal_res}×{internal_res}', (p, acc + 0.5), 
                   ha='center', fontsize=9, color='gray')
    
    ax.set_ylim(90, 100)
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.show()


def plot_architecture_diagram(save_path=None):
    
    fig, ax = plt.subplots(figsize=(14, 4))
    ax.set_xlim(0, 14)
    ax.set_ylim(0, 4)
    ax.axis('off')
    
    # Colors
    colors = {
        'patch': '#FFB347',
        'depthwise': '#87CEEB',
        'pointwise': '#98FB98',
        'pool': '#DDA0DD',
        'fc': '#F0E68C'
    }
    
    # Draw boxes
    boxes = [
        (0.5, 1.5, 2, 1, 'Patch\nEmbedding', colors['patch']),
        (3, 1.5, 2, 1, 'Depthwise\nConv', colors['depthwise']),
        (5.5, 1.5, 2, 1, 'Pointwise\nConv', colors['pointwise']),
        (9, 1.5, 1.5, 1, 'Global\nPool', colors['pool']),
        (11, 1.5, 1.5, 1, 'FC', colors['fc']),
    ]
    
    for x, y, w, h, text, color in boxes:
        rect = plt.Rectangle((x, y), w, h, facecolor=color, edgecolor='black', linewidth=2)
        ax.add_patch(rect)
        ax.text(x + w/2, y + h/2, text, ha='center', va='center', fontsize=10, fontweight='bold')
    
    # Arrows
    arrows = [(2.5, 2), (5, 2), (7.5, 2), (8.7, 2), (10.5, 2), (12.5, 2)]
    for i in range(len(arrows)-1):
        ax.annotate('', xy=(arrows[i+1][0], arrows[i+1][1]), xytext=(arrows[i][0], arrows[i][1]),
                   arrowprops=dict(arrowstyle='->', color='black', lw=2))
    
    # Depth label
    ax.annotate('', xy=(7.5, 0.8), xytext=(3, 0.8),
               arrowprops=dict(arrowstyle='<->', color='gray', lw=1.5))
    ax.text(5.25, 0.4, '× depth', ha='center', fontsize=10, color='gray')
    
    # Residual connection
    ax.annotate('', xy=(5.5, 2.7), xytext=(3, 2.7),
               arrowprops=dict(arrowstyle='->', color='red', lw=1.5, 
                             connectionstyle='arc3,rad=0.3'))
    ax.text(4.25, 3.2, 'residual', ha='center', fontsize=9, color='red')
    
    ax.set_title('ConvMixer Architecture', fontsize=14, fontweight='bold', pad=20)
    
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.show()


def create_results_table(results, title='Results'):
   
    print(f"\n{'='*60}")
    print(f"{title:^60}")
    print(f"{'='*60}")
    
    if not results:
        print("No results available")
        return
    
    # Get all keys
    keys = list(results[0].keys())
    
    # Header
    header = '|'.join([f'{k:^15}' for k in keys])
    print(f"|{header}|")
    print(f"|{'-'*15}|" * len(keys))
    
    # Rows
    for row in results:
        values = '|'.join([f'{str(row[k]):^15}' for k in keys])
        print(f"|{values}|")
    
    print(f"{'='*60}\n")


def save_results_json(results, filepath):
    """Save results to JSON file."""
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, 'w') as f:
        json.dump(results, f, indent=2)
    print(f"Results saved to {filepath}")


def load_results_json(filepath):
    """Load results from JSON file."""
    with open(filepath, 'r') as f:
        return json.load(f)


if __name__ == "__main__":
    # Test visualization functions
    print("Testing visualization functions...")
    
    # Test training curves
    history = {
        'train_loss': [2.0, 1.5, 1.2, 1.0, 0.8],
        'train_acc': [30, 50, 65, 75, 82],
        'test_acc': [28, 48, 62, 72, 78]
    }
    plot_training_curves(history, title='Test Training Curves')
    
    # Test kernel size comparison
    our_kernel = {3: 92.5, 5: 94.2, 7: 95.1, 9: 95.5}
    paper_kernel = {3: 93.61, 5: 95.19, 7: 95.80, 9: 95.88}
    plot_kernel_size_comparison(our_kernel, paper_kernel)
    
    # Test architecture diagram
    plot_architecture_diagram()
    
    print("All tests passed!")
