"""
Configuration file for ConvMixer experiments.

This module centralizes all hyperparameters for easy experimentation.

Date: 12/11/2025
Written by [Minghao Liu] <ml5312@columbia.edu>

The code has not been generated by AI tools, or copied from an exteranal resource.
"""

from dataclasses import dataclass
from typing import Optional


@dataclass
class ModelConfig:
    """ConvMixer model configuration."""
    dim: int = 256
    depth: int = 8
    kernel_size: int = 9
    patch_size: int = 1
    num_classes: int = 10
    in_channels: int = 3


@dataclass
class TrainingConfig:
    """Training configuration."""
    epochs: int = 200
    batch_size: int = 64
    learning_rate: float = 0.01
    weight_decay: float = 0.01
    
    # Learning rate schedule
    lr_schedule: str = 'triangular'  # 'triangular' or 'cosine'
    warmup_epochs: int = 5
    
    # Gradient clipping
    clip_grad_norm: float = 1.0
    
    # Data augmentation
    use_mixup: bool = True
    mixup_alpha: float = 0.8
    use_cutmix: bool = True
    cutmix_alpha: float = 1.0
    use_randaugment: bool = True
    randaugment_n: int = 2
    randaugment_m: int = 9


@dataclass
class ExperimentConfig:
    """Full experiment configuration."""
    model: ModelConfig
    training: TrainingConfig
    
    # Experiment settings
    experiment_name: str = "convmixer_baseline"
    seed: int = 42
    device: str = "cuda"
    
    # Logging
    log_dir: str = "./logs"
    save_checkpoint: bool = True
    checkpoint_dir: str = "./checkpoints"


# Predefined configurations matching the paper
CONFIGS = {
    # CIFAR-10 configurations from Table 4
    'cifar10_256_8': ExperimentConfig(
        model=ModelConfig(dim=256, depth=8, kernel_size=9, patch_size=1),
        training=TrainingConfig(epochs=200),
        experiment_name="convmixer_256_8"
    ),
    
    'cifar10_256_8_k3': ExperimentConfig(
        model=ModelConfig(dim=256, depth=8, kernel_size=3, patch_size=1),
        training=TrainingConfig(epochs=200),
        experiment_name="convmixer_256_8_k3"
    ),
    
    'cifar10_256_8_k5': ExperimentConfig(
        model=ModelConfig(dim=256, depth=8, kernel_size=5, patch_size=1),
        training=TrainingConfig(epochs=200),
        experiment_name="convmixer_256_8_k5"
    ),
    
    'cifar10_256_8_k7': ExperimentConfig(
        model=ModelConfig(dim=256, depth=8, kernel_size=7, patch_size=1),
        training=TrainingConfig(epochs=200),
        experiment_name="convmixer_256_8_k7"
    ),
    
    'cifar10_256_8_p2': ExperimentConfig(
        model=ModelConfig(dim=256, depth=8, kernel_size=9, patch_size=2),
        training=TrainingConfig(epochs=200),
        experiment_name="convmixer_256_8_p2"
    ),
    
    'cifar10_256_8_p4': ExperimentConfig(
        model=ModelConfig(dim=256, depth=8, kernel_size=9, patch_size=4),
        training=TrainingConfig(epochs=200),
        experiment_name="convmixer_256_8_p4"
    ),
    
    # Quick test configuration (for debugging)
    'cifar10_quick': ExperimentConfig(
        model=ModelConfig(dim=128, depth=4, kernel_size=5, patch_size=4),
        training=TrainingConfig(epochs=10, batch_size=128),
        experiment_name="convmixer_quick_test"
    ),
}


def get_config(name: str) -> ExperimentConfig:
    """Get a predefined configuration by name."""
    if name not in CONFIGS:
        raise ValueError(f"Unknown config: {name}. Available: {list(CONFIGS.keys())}")
    return CONFIGS[name]


def print_config(config: ExperimentConfig):
    """Print configuration details."""
    print("="*50)
    print(f"Experiment: {config.experiment_name}")
    print("="*50)
    print("\nModel:")
    print(f"  dim: {config.model.dim}")
    print(f"  depth: {config.model.depth}")
    print(f"  kernel_size: {config.model.kernel_size}")
    print(f"  patch_size: {config.model.patch_size}")
    print("\nTraining:")
    print(f"  epochs: {config.training.epochs}")
    print(f"  batch_size: {config.training.batch_size}")
    print(f"  learning_rate: {config.training.learning_rate}")
    print(f"  weight_decay: {config.training.weight_decay}")
    print("="*50)


if __name__ == "__main__":
    # Test configurations
    for name in CONFIGS:
        config = get_config(name)
        print(f"\n{name}:")
        print(f"  Model: ConvMixer-{config.model.dim}/{config.model.depth}")
        print(f"  k={config.model.kernel_size}, p={config.model.patch_size}")
